version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - ls -la 
      - ls -la target
      - cd target
      - mv my-web-app.war my-web-app.zip
      - aws s3 cp my-web-app.zip s3://andmerwe-codebuild/
      - mkdir eb-app
      - unzip -d eb-app my-web-app.zip
      - ls -la eb-app/
      - sed -i 's/Hello World!/Congratulations you have deployed a simple Tomcat application using CodePipeline, CodeBuild and Elastic Beanstalk!/g' eb-app/index.jsp
artifacts:
  files:
   - eb-app/**/*