AWSTemplateFormatVersion: "2010-09-09"
Description:
  This template sets up the sample calculator application on an AutoScaling group,
  behind an Application Load Balancer, with a CodeDeploy application.

Parameters:
  BuildName:
    Type: String
    Default: 'CodeBuildVLSDemo'
    Description: 'Specify a name for the CodeBuild project'
  CodeCommitRepo:
    Type: String
    Default: 'CI_CD'
    Description: 'Name of the repo created in Lab 1'

Resources:
  CodeBuildPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:PutObject
          - s3:GetObject
          - s3:GetObjectVersion
          Effect: Allow
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - '*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - '*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - '*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - '*'
        - Action:
          - codecommit:GitPull
          Effect: Allow
          Resource:
          - !Join
            - ':'
            - - arn
              - aws
              - codecommit
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - '*'
        - Action:
          - kms:GenerateDataKey*
          - kms:Encrypt
          - kms:Decrypt
          Effect: Allow
          Resource:
          - !Join
            - ':'
            - - arn:aws:kms
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - !Join
                - /
                - - alias
                  - aws/s3
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
      - !Ref 'CodeBuildRole'
    Type: AWS::IAM::Policy

  CodeBuildRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild
    Type: AWS::IAM::Role

  NodeTestingBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Ref BuildName
      Description: Build project for unit testing
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:3.0
      Source:
        Type: CODECOMMIT
      TimeoutInMinutes: 15
      Tags:
        - Key: Lab
          Value: 04-pipeline
        - Key: Component
          Value: CodeBuild